ALTER TABLE conversation
  ADD COLUMN IF NOT EXISTS deleted_by_buyer BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE conversation
  ADD COLUMN IF NOT EXISTS deleted_by_seller BOOLEAN NOT NULL DEFAULT FALSE;
